# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{iarea}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoji Shidara"]
  s.date = %q{2010-04-26}
  s.description = %q{A library for DoCoMo Open Iarea.}
  s.email = %q{dara@shidara.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "db/iareadata.sqlite3",
     "iarea.gemspec",
     "lib/iarea.rb",
     "lib/tasks/iarea.rake",
     "test/iarea/iarea_test.rb",
     "test/test_helper.rb",
     "tools/import_meshes.rb"
  ]
  s.homepage = %q{http://github.com/darashi/iarea}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6.1}
  s.summary = %q{A library for DoCoMo Open Iarea.}
  s.test_files = [
    "test/iarea/iarea_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 3.10.0"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 1.2.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<sequel>, [">= 3.10.0"])
      s.add_dependency(%q<sqlite3>, [">= 1.2.5"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 3.10.0"])
    s.add_dependency(%q<sqlite3>, [">= 1.2.5"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

